name: Check Files
on: [push, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract and List
        run: |
          unzip verbi.zip
          echo "=== ЧТО СЕЙЧАС В КОРНЕ ==="
          ls -la
          echo "=== ПРОБУЕМ НАЙТИ GRADLEY ==="
          find . -name "gradlew"
          
